maintel:
  driver_type: feature_scheduler
  mode: ADVANCE
  startup_type: COLD
  startup_database: /home/saluser/rubin_sim_data/preops_lsst_fbs_observations.sql
  feature_scheduler_driver_configuration:
    observation_database_name: /home/saluser/rubin_sim_data/preops_lsst_fbs_observations.sql
    scheduler_config: /net/obs-env/auto_base_packages/ts_config_scheduler/Scheduler/feature_scheduler/maintel/fbs_config_lsst_survey.py
